-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ReadModel.Object exposing (Challenges(..), Color(..), Game_state(..), Games(..), Player(..))


type Challenges
    = Challenges


type Color
    = Color


type Game_state
    = Game_state


type Games
    = Games


type Player
    = Player
