-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ReadModel.ScalarCodecs exposing (Id, Int4_, Uuid, codecs)

import Json.Decode as Decode exposing (Decoder)
import ReadModel.Scalar exposing (defaultCodecs)


type alias Id =
    ReadModel.Scalar.Id


type alias Int4_ =
    ReadModel.Scalar.Int4_


type alias Uuid =
    ReadModel.Scalar.Uuid


codecs : ReadModel.Scalar.Codecs Id Int4_ Uuid
codecs =
    ReadModel.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecInt4_ = defaultCodecs.codecInt4_
        , codecUuid = defaultCodecs.codecUuid
        }
