-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ReadModel.VerifyScalarCodecs exposing (verify)

{-
   This file is intended to be used to ensure that custom scalar decoder
   files are valid. It is compiled using `elm make` by the CLI.
-}

import ReadModel.Scalar
import ScalarCodecs


verify : ReadModel.Scalar.Codecs ScalarCodecs.Id ScalarCodecs.Int4_ ScalarCodecs.Uuid
verify =
    ScalarCodecs.codecs
