  
language: elm

install:
  - npm install -g create-elm-app@4.2.1

script:
  - npm install
  - ELM_APP_GRAPHQL_URI="salamander-hasura.herokuapp.com/v1/graphql" ELM_APP_CMD_URI="cosmic-ray-api.herokuapp.com" npx elm-app build
  - mv ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: cosmic-ray.surge.sh
  skip_cleanup: true
