-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ReadModel.Enum.Color_enum exposing (Color_enum(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


type Color_enum
    = Red
    | Yellow


list : List Color_enum
list =
    [ Red, Yellow ]


decoder : Decoder Color_enum
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "red" ->
                        Decode.succeed Red

                    "yellow" ->
                        Decode.succeed Yellow

                    _ ->
                        Decode.fail ("Invalid Color_enum type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Color_enum -> String
toString enum =
    case enum of
        Red ->
            "red"

        Yellow ->
            "yellow"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Color_enum
fromString enumString =
    case enumString of
        "red" ->
            Just Red

        "yellow" ->
            Just Yellow

        _ ->
            Nothing
