-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ReadModel.Enum.Games_select_column exposing (Games_select_column(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "games"

  - Game\_state - column name
  - Id - column name
  - Moves - column name
  - Player - column name
  - Serial\_id - column name

-}
type Games_select_column
    = Game_state
    | Id
    | Moves
    | Player
    | Serial_id


list : List Games_select_column
list =
    [ Game_state, Id, Moves, Player, Serial_id ]


decoder : Decoder Games_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "game_state" ->
                        Decode.succeed Game_state

                    "id" ->
                        Decode.succeed Id

                    "moves" ->
                        Decode.succeed Moves

                    "player" ->
                        Decode.succeed Player

                    "serial_id" ->
                        Decode.succeed Serial_id

                    _ ->
                        Decode.fail ("Invalid Games_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Games_select_column -> String
toString enum =
    case enum of
        Game_state ->
            "game_state"

        Id ->
            "id"

        Moves ->
            "moves"

        Player ->
            "player"

        Serial_id ->
            "serial_id"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Games_select_column
fromString enumString =
    case enumString of
        "game_state" ->
            Just Game_state

        "id" ->
            Just Id

        "moves" ->
            Just Moves

        "player" ->
            Just Player

        "serial_id" ->
            Just Serial_id

        _ ->
            Nothing
