-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ReadModel.Enum.Player_enum exposing (Player_enum(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


type Player_enum
    = None
    | Red
    | Yellow


list : List Player_enum
list =
    [ None, Red, Yellow ]


decoder : Decoder Player_enum
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "none" ->
                        Decode.succeed None

                    "red" ->
                        Decode.succeed Red

                    "yellow" ->
                        Decode.succeed Yellow

                    _ ->
                        Decode.fail ("Invalid Player_enum type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Player_enum -> String
toString enum =
    case enum of
        None ->
            "none"

        Red ->
            "red"

        Yellow ->
            "yellow"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Player_enum
fromString enumString =
    case enumString of
        "none" ->
            Just None

        "red" ->
            Just Red

        "yellow" ->
            Just Yellow

        _ ->
            Nothing
