-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ReadModel.Object.Challenges exposing (color, colorByColor, id, serial_id)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ReadModel.Enum.Color_enum
import ReadModel.InputObject
import ReadModel.Interface
import ReadModel.Object
import ReadModel.Scalar
import ReadModel.Union
import ScalarCodecs


color : SelectionSet ReadModel.Enum.Color_enum.Color_enum ReadModel.Object.Challenges
color =
    Object.selectionForField "Enum.Color_enum.Color_enum" "color" [] ReadModel.Enum.Color_enum.decoder


{-| An object relationship
-}
colorByColor : SelectionSet decodesTo ReadModel.Object.Color -> SelectionSet decodesTo ReadModel.Object.Challenges
colorByColor object_ =
    Object.selectionForCompositeField "colorByColor" [] object_ identity


id : SelectionSet ScalarCodecs.Uuid ReadModel.Object.Challenges
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (ScalarCodecs.codecs |> ReadModel.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


serial_id : SelectionSet Int ReadModel.Object.Challenges
serial_id =
    Object.selectionForField "Int" "serial_id" [] Decode.int
