-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ReadModel.Object.Color exposing (ChallengesOptionalArguments, challenges, value)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ReadModel.Enum.Challenges_select_column
import ReadModel.InputObject
import ReadModel.Interface
import ReadModel.Object
import ReadModel.Scalar
import ReadModel.Union
import ScalarCodecs


type alias ChallengesOptionalArguments =
    { distinct_on : OptionalArgument (List ReadModel.Enum.Challenges_select_column.Challenges_select_column)
    , limit : OptionalArgument Int
    , offset : OptionalArgument Int
    , order_by : OptionalArgument (List ReadModel.InputObject.Challenges_order_by)
    , where_ : OptionalArgument ReadModel.InputObject.Challenges_bool_exp
    }


{-| An array relationship

  - distinct\_on - distinct select on columns
  - limit - limit the number of rows returned
  - offset - skip the first n rows. Use only with order\_by
  - order\_by - sort the rows by one or more columns
  - where\_ - filter the rows returned

-}
challenges : (ChallengesOptionalArguments -> ChallengesOptionalArguments) -> SelectionSet decodesTo ReadModel.Object.Challenges -> SelectionSet (List decodesTo) ReadModel.Object.Color
challenges fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { distinct_on = Absent, limit = Absent, offset = Absent, order_by = Absent, where_ = Absent }

        optionalArgs =
            [ Argument.optional "distinct_on" filledInOptionals.distinct_on (Encode.enum ReadModel.Enum.Challenges_select_column.toString |> Encode.list), Argument.optional "limit" filledInOptionals.limit Encode.int, Argument.optional "offset" filledInOptionals.offset Encode.int, Argument.optional "order_by" filledInOptionals.order_by (ReadModel.InputObject.encodeChallenges_order_by |> Encode.list), Argument.optional "where" filledInOptionals.where_ ReadModel.InputObject.encodeChallenges_bool_exp ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "challenges" optionalArgs object_ (identity >> Decode.list)


value : SelectionSet String ReadModel.Object.Color
value =
    Object.selectionForField "String" "value" [] Decode.string
